#!/usr/bin/env python3
"""Add image-identify questions to each topic in questions.yaml."""

import yaml
import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(SCRIPT_DIR)
YAML_PATH = os.path.join(PROJECT_ROOT, "data", "questions.yaml")

# Image questions organized by topic, based on notes + OCR analysis of each image
IMAGE_QUESTIONS = {
    "intro-body-orientation": [
        {
            "image": "image53.png",
            "highlight": {"x": 30, "y": 30},
            "question": "Which type of muscle is voluntary and attached to bones?",
            "answer": "Skeletal muscle",
            "written_accept": ["skeletal muscle", "skeletal"],
            "distractors": ["Smooth muscle", "Cardiac muscle", "Connective tissue", "Elastic muscle"],
        },
        {
            "image": "image53.png",
            "highlight": {"x": 30, "y": 60},
            "question": "Which type of muscle is involuntary and found in walls of hollow organs?",
            "answer": "Smooth muscle",
            "written_accept": ["smooth muscle", "smooth"],
            "distractors": ["Skeletal muscle", "Cardiac muscle", "Striated muscle", "Voluntary muscle"],
        },
        {
            "image": "image53.png",
            "highlight": {"x": 30, "y": 80},
            "question": "Which type of muscle is found only in the heart and has its own electrical conduction?",
            "answer": "Cardiac muscle",
            "written_accept": ["cardiac muscle", "cardiac"],
            "distractors": ["Skeletal muscle", "Smooth muscle", "Striated muscle", "Voluntary muscle"],
        },
    ],
    "anatomical-movements": [
        {
            "image": "image101.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the joint shown here that connects the clavicle to the scapula.",
            "answer": "Acromioclavicular (AC) joint",
            "written_accept": ["acromioclavicular joint", "ac joint", "acromioclavicular"],
            "distractors": ["Sternoclavicular joint", "Glenohumeral joint", "Scapulothoracic joint"],
        },
        {
            "image": "image8.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the main ball-and-socket joint of the shoulder shown here.",
            "answer": "Glenohumeral joint",
            "written_accept": ["glenohumeral joint", "glenohumeral", "shoulder joint"],
            "distractors": ["Acromioclavicular joint", "Sternoclavicular joint", "Scapulothoracic joint"],
        },
        {
            "image": "image56.png",
            "highlight": {"x": 50, "y": 60},
            "question": "Identify the joint formed between the scapula and the thoracic wall.",
            "answer": "Scapulothoracic joint",
            "written_accept": ["scapulothoracic joint", "scapulothoracic"],
            "distractors": ["Glenohumeral joint", "Acromioclavicular joint", "Sternoclavicular joint"],
        },
        {
            "image": "image30.png",
            "highlight": {"x": 40, "y": 50},
            "question": "Identify the joint between the humerus and ulna shown here.",
            "answer": "Humeroulnar joint",
            "written_accept": ["humeroulnar joint", "humeroulnar"],
            "distractors": ["Humeroradial joint", "Proximal radioulnar joint", "Glenohumeral joint", "Elbow joint"],
        },
        {
            "image": "image79.png",
            "highlight": {"x": 60, "y": 70},
            "question": "Identify the joint between the radius and ulna near the elbow.",
            "answer": "Proximal radioulnar joint",
            "written_accept": ["proximal radioulnar joint", "proximal radioulnar"],
            "distractors": ["Humeroulnar joint", "Humeroradial joint", "Distal radioulnar joint", "Wrist joint"],
        },
        {
            "image": "image58.png",
            "highlight": {"x": 40, "y": 25},
            "question": "Identify the type of finger joints at the base of each finger where the metacarpal meets the phalanx.",
            "answer": "MCP joints (metacarpophalangeal)",
            "written_accept": ["mcp joints", "mcp", "metacarpophalangeal joints", "metacarpophalangeal"],
            "distractors": ["PIP joints", "DIP joints", "Carpometacarpal joints", "Interphalangeal joints"],
        },
        {
            "image": "image58.png",
            "highlight": {"x": 40, "y": 50},
            "question": "Identify the middle finger joints between the proximal and middle phalanges.",
            "answer": "PIP joints (proximal interphalangeal)",
            "written_accept": ["pip joints", "pip", "proximal interphalangeal joints", "proximal interphalangeal"],
            "distractors": ["MCP joints", "DIP joints", "Carpometacarpal joints"],
        },
        {
            "image": "image58.png",
            "highlight": {"x": 40, "y": 75},
            "question": "Identify the finger joints closest to the fingertips.",
            "answer": "DIP joints (distal interphalangeal)",
            "written_accept": ["dip joints", "dip", "distal interphalangeal joints", "distal interphalangeal"],
            "distractors": ["MCP joints", "PIP joints", "Carpometacarpal joints"],
        },
        {
            "image": "image5.png",
            "highlight": {"x": 50, "y": 40},
            "question": "What movement of the shoulder brings the arm straight forward?",
            "answer": "Shoulder flexion",
            "written_accept": ["shoulder flexion", "flexion"],
            "distractors": ["Shoulder extension", "Shoulder abduction", "Shoulder adduction", "Shoulder rotation"],
        },
        {
            "image": "image124.png",
            "highlight": {"x": 50, "y": 50},
            "question": "What movement at the hip brings the leg straight backward?",
            "answer": "Hip extension",
            "written_accept": ["hip extension", "extension"],
            "distractors": ["Hip flexion", "Hip abduction", "Hip adduction", "Hip rotation"],
        },
        {
            "image": "image55.png",
            "highlight": {"x": 50, "y": 50},
            "question": "What scapular movement involves squeezing the shoulder blades together?",
            "answer": "Retraction",
            "written_accept": ["retraction", "scapular retraction"],
            "distractors": ["Protraction", "Elevation", "Depression", "Upward rotation"],
        },
        {
            "image": "image12.png",
            "highlight": {"x": 50, "y": 50},
            "question": "What ankle movement points the toes downward, like pressing a gas pedal?",
            "answer": "Plantarflexion",
            "written_accept": ["plantarflexion", "plantar flexion"],
            "distractors": ["Dorsiflexion", "Eversion", "Inversion", "Ankle extension"],
        },
        {
            "image": "image48.png",
            "highlight": {"x": 50, "y": 50},
            "question": "What neck movement brings the chin to the chest?",
            "answer": "Neck flexion",
            "written_accept": ["neck flexion", "flexion", "cervical flexion"],
            "distractors": ["Neck extension", "Lateral flexion", "Neck rotation", "Neck protraction"],
        },
        {
            "image": "image33.png",
            "highlight": {"x": 50, "y": 50},
            "question": "What ankle movement angles the sole of the foot outward?",
            "answer": "Eversion",
            "written_accept": ["eversion"],
            "distractors": ["Inversion", "Plantarflexion", "Dorsiflexion", "Pronation"],
        },
    ],
    "thorax-1": [
        {
            "image": "image6.png",
            "highlight": {"x": 35, "y": 20},
            "question": "Identify the superior part of the sternum shown here.",
            "answer": "Manubrium",
            "written_accept": ["manubrium"],
            "distractors": ["Body of sternum", "Xiphoid process", "Sternal angle", "Costal cartilage"],
        },
        {
            "image": "image6.png",
            "highlight": {"x": 35, "y": 50},
            "question": "Identify the middle and largest part of the sternum.",
            "answer": "Body of the sternum",
            "written_accept": ["body", "body of sternum", "body of the sternum", "sternal body"],
            "distractors": ["Manubrium", "Xiphoid process", "Sternal angle", "Costal cartilage"],
        },
        {
            "image": "image6.png",
            "highlight": {"x": 35, "y": 85},
            "question": "Identify the small inferior projection at the bottom of the sternum.",
            "answer": "Xiphoid process",
            "written_accept": ["xiphoid process", "xiphoid"],
            "distractors": ["Manubrium", "Body of sternum", "Costal cartilage", "Sternal angle"],
        },
        {
            "image": "image131.png",
            "highlight": {"x": 50, "y": 35},
            "question": "Identify the angle between the manubrium and body of the sternum, at the level of the 2nd costal cartilage.",
            "answer": "Sternal angle (Angle of Louis)",
            "written_accept": ["sternal angle", "angle of louis", "angle of louie", "manubriosternal joint"],
            "distractors": ["Jugular notch", "Xiphoid process", "Costal margin", "Intercostal space"],
        },
        {
            "image": "image83.png",
            "highlight": {"x": 50, "y": 30},
            "question": "This diagram shows areas of skin innervated by individual spinal nerves. What are these areas called?",
            "answer": "Dermatomes",
            "written_accept": ["dermatomes", "dermatome"],
            "distractors": ["Myotomes", "Sclerotomes", "Nerve plexuses", "Cutaneous branches"],
        },
        {
            "image": "image80.png",
            "highlight": {"x": 50, "y": 45},
            "question": "According to the dermatome map, which spinal nerve level corresponds to the nipple line?",
            "answer": "T4",
            "written_accept": ["t4"],
            "distractors": ["T2", "T6", "T7", "T10"],
        },
        {
            "image": "image80.png",
            "highlight": {"x": 50, "y": 65},
            "question": "According to the dermatome map, which spinal nerve level corresponds to the xiphisternal junction?",
            "answer": "T7",
            "written_accept": ["t7"],
            "distractors": ["T4", "T6", "T10", "T12"],
        },
        {
            "image": "image17.png",
            "highlight": {"x": 40, "y": 50},
            "question": "Identify the smaller chest wall muscle that attaches to the coracoid process and ribs 3-5.",
            "answer": "Pectoralis minor",
            "written_accept": ["pectoralis minor", "pec minor"],
            "distractors": ["Pectoralis major", "Serratus anterior", "Deltoid", "Subclavius"],
        },
        {
            "image": "image109.png",
            "highlight": {"x": 30, "y": 30},
            "question": "Identify the large anterior chest wall muscle shown here that attaches to the sternum, clavicle, and humerus.",
            "answer": "Pectoralis major",
            "written_accept": ["pectoralis major", "pec major"],
            "distractors": ["Pectoralis minor", "Serratus anterior", "Deltoid", "Latissimus dorsi"],
        },
        {
            "image": "image135.png",
            "highlight": {"x": 50, "y": 30},
            "question": "In the intercostal neurovascular bundle, identify the order of structures from superior to inferior along the rib.",
            "answer": "Vein, Artery, Nerve (VAN)",
            "written_accept": ["van", "vein artery nerve", "intercostal vein artery nerve"],
            "distractors": ["Artery, Vein, Nerve", "Nerve, Artery, Vein", "Nerve, Vein, Artery"],
        },
        {
            "image": "image127.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the central compartment of the thorax between the two pleural cavities.",
            "answer": "Mediastinum",
            "written_accept": ["mediastinum"],
            "distractors": ["Pleural cavity", "Pericardial cavity", "Thoracic duct", "Pulmonary hilum"],
        },
        {
            "image": "image61.png",
            "highlight": {"x": 40, "y": 40},
            "question": "Identify the layer of pleura that directly covers the lung surface.",
            "answer": "Visceral pleura",
            "written_accept": ["visceral pleura", "visceral"],
            "distractors": ["Parietal pleura", "Fibrous pericardium", "Endothoracic fascia", "Serous membrane"],
        },
        {
            "image": "image61.png",
            "highlight": {"x": 70, "y": 40},
            "question": "Identify the layer of pleura that lines the inside of the chest wall.",
            "answer": "Parietal pleura",
            "written_accept": ["parietal pleura", "parietal"],
            "distractors": ["Visceral pleura", "Fibrous pericardium", "Endothoracic fascia", "Serous membrane"],
        },
        {
            "image": "image2.png",
            "highlight": {"x": 50, "y": 15},
            "question": "How many lobes does the right lung have?",
            "answer": "Three lobes",
            "written_accept": ["three", "3", "three lobes", "3 lobes"],
            "distractors": ["Two lobes", "Four lobes", "One lobe", "Five lobes"],
        },
        {
            "image": "image2.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the fissure that separates the upper and middle lobes of the right lung.",
            "answer": "Horizontal fissure",
            "written_accept": ["horizontal fissure", "horizontal"],
            "distractors": ["Oblique fissure", "Transverse fissure", "Cardiac notch", "Hilum"],
        },
        {
            "image": "image90.png",
            "highlight": {"x": 50, "y": 15},
            "question": "How many lobes does the left lung have?",
            "answer": "Two lobes",
            "written_accept": ["two", "2", "two lobes", "2 lobes"],
            "distractors": ["Three lobes", "Four lobes", "One lobe", "Five lobes"],
        },
        {
            "image": "image103.png",
            "highlight": {"x": 20, "y": 50},
            "question": "Identify the subdivision of the inferior mediastinum located between the pericardium and sternum.",
            "answer": "Anterior mediastinum",
            "written_accept": ["anterior mediastinum", "anterior"],
            "distractors": ["Middle mediastinum", "Posterior mediastinum", "Superior mediastinum"],
        },
        {
            "image": "image103.png",
            "highlight": {"x": 75, "y": 50},
            "question": "Identify the subdivision of the inferior mediastinum posterior to the pericardium, containing the descending aorta and esophagus.",
            "answer": "Posterior mediastinum",
            "written_accept": ["posterior mediastinum", "posterior"],
            "distractors": ["Anterior mediastinum", "Middle mediastinum", "Superior mediastinum"],
        },
        {
            "image": "image23.png",
            "highlight": {"x": 15, "y": 15},
            "question": "Identify the large vein shown at the top right of the heart that returns deoxygenated blood from the upper body.",
            "answer": "Superior vena cava",
            "written_accept": ["superior vena cava", "svc"],
            "distractors": ["Inferior vena cava", "Pulmonary trunk", "Aorta", "Pulmonary vein"],
        },
        {
            "image": "image23.png",
            "highlight": {"x": 30, "y": 15},
            "question": "Identify the vessel that carries deoxygenated blood from the right ventricle to the lungs.",
            "answer": "Pulmonary trunk",
            "written_accept": ["pulmonary trunk", "pulmonary artery"],
            "distractors": ["Aorta", "Superior vena cava", "Pulmonary vein", "Inferior vena cava"],
        },
        {
            "image": "image23.png",
            "highlight": {"x": 80, "y": 60},
            "question": "Identify the chamber of the heart shown on the right side that receives blood from the vena cava.",
            "answer": "Right atrium",
            "written_accept": ["right atrium", "ra"],
            "distractors": ["Left atrium", "Right ventricle", "Left ventricle"],
        },
        {
            "image": "image23.png",
            "highlight": {"x": 55, "y": 80},
            "question": "Identify the muscular chamber shown at the lower left that pumps blood into the aorta.",
            "answer": "Left ventricle",
            "written_accept": ["left ventricle", "lv"],
            "distractors": ["Right ventricle", "Left atrium", "Right atrium"],
        },
        {
            "image": "image120.png",
            "highlight": {"x": 30, "y": 50},
            "question": "Identify the coronary artery that runs in the anterior interventricular sulcus, also called the LAD.",
            "answer": "Left anterior descending artery (LAD)",
            "written_accept": ["left anterior descending", "lad", "anterior interventricular artery"],
            "distractors": ["Circumflex artery", "Right coronary artery", "Right marginal artery", "Posterior interventricular artery"],
        },
        {
            "image": "image120.png",
            "highlight": {"x": 50, "y": 30},
            "question": "Identify the coronary artery that wraps around the left side of the heart posteriorly.",
            "answer": "Circumflex artery",
            "written_accept": ["circumflex artery", "circumflex"],
            "distractors": ["Left anterior descending artery", "Right coronary artery", "Right marginal artery", "Posterior interventricular artery"],
        },
        {
            "image": "image120.png",
            "highlight": {"x": 75, "y": 40},
            "question": "Identify the coronary artery that runs between the right atrium and right ventricle.",
            "answer": "Right coronary artery",
            "written_accept": ["right coronary artery", "rca"],
            "distractors": ["Left coronary artery", "Circumflex artery", "Left anterior descending artery"],
        },
        {
            "image": "image120.png",
            "highlight": {"x": 70, "y": 75},
            "question": "Identify the artery that runs along the inferior border of the right ventricle, branching from the right coronary artery.",
            "answer": "Right marginal artery",
            "written_accept": ["right marginal artery", "right marginal"],
            "distractors": ["Left anterior descending artery", "Circumflex artery", "Posterior interventricular artery"],
        },
        {
            "image": "image87.png",
            "highlight": {"x": 40, "y": 50},
            "question": "Identify the large vein that runs alongside the LAD and drains cardiac blood.",
            "answer": "Great cardiac vein",
            "written_accept": ["great cardiac vein"],
            "distractors": ["Middle cardiac vein", "Coronary sinus", "Small cardiac vein", "Anterior cardiac vein"],
        },
        {
            "image": "image73.png",
            "highlight": {"x": 50, "y": 30},
            "question": "Identify the main airway structure that branches into the left and right lungs.",
            "answer": "Trachea",
            "written_accept": ["trachea"],
            "distractors": ["Bronchus", "Larynx", "Pharynx", "Esophagus"],
        },
        {
            "image": "image149.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the membrane that wraps around the heart, shown here enclosing the cardiac structures.",
            "answer": "Pericardium",
            "written_accept": ["pericardium", "pericardial sac"],
            "distractors": ["Pleura", "Endocardium", "Myocardium", "Epicardium"],
        },
    ],
    "thorax-2": [
        {
            "image": "image123.png",
            "highlight": {"x": 25, "y": 40},
            "question": "Identify the upper-right chamber of the heart that receives deoxygenated blood.",
            "answer": "Right atrium",
            "written_accept": ["right atrium", "ra"],
            "distractors": ["Left atrium", "Right ventricle", "Left ventricle"],
        },
        {
            "image": "image123.png",
            "highlight": {"x": 75, "y": 40},
            "question": "Identify the upper-left chamber of the heart that receives oxygenated blood from the lungs.",
            "answer": "Left atrium",
            "written_accept": ["left atrium", "la"],
            "distractors": ["Right atrium", "Left ventricle", "Right ventricle"],
        },
        {
            "image": "image123.png",
            "highlight": {"x": 25, "y": 75},
            "question": "Identify the lower-right chamber of the heart that pumps blood to the lungs.",
            "answer": "Right ventricle",
            "written_accept": ["right ventricle", "rv"],
            "distractors": ["Left ventricle", "Right atrium", "Left atrium"],
        },
        {
            "image": "image123.png",
            "highlight": {"x": 75, "y": 75},
            "question": "Identify the lower-left chamber of the heart that pumps blood to the body via the aorta.",
            "answer": "Left ventricle",
            "written_accept": ["left ventricle", "lv"],
            "distractors": ["Right ventricle", "Left atrium", "Right atrium"],
        },
        {
            "image": "image16.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the internal feature of the right atrium consisting of ridged muscle fibers.",
            "answer": "Pectinate muscle",
            "written_accept": ["pectinate muscle", "pectinate muscles"],
            "distractors": ["Trabeculae carneae", "Papillary muscle", "Chordae tendineae", "Fossa ovalis"],
        },
        {
            "image": "image108.png",
            "highlight": {"x": 50, "y": 60},
            "question": "Identify the fibrous strings in the right ventricle that connect the valve cusps to the papillary muscles.",
            "answer": "Chordae tendineae",
            "written_accept": ["chordae tendineae", "chordae"],
            "distractors": ["Pectinate muscle", "Trabeculae carneae", "Papillary muscle", "Fossa ovalis"],
        },
        {
            "image": "image104.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Which ventricle has a much thicker muscular wall, as shown in this cross-section?",
            "answer": "Left ventricle",
            "written_accept": ["left ventricle", "lv"],
            "distractors": ["Right ventricle", "Right atrium", "Left atrium"],
        },
        {
            "image": "image111.png",
            "highlight": {"x": 30, "y": 25},
            "question": "Identify the pacemaker node of the heart that initiates the electrical impulse.",
            "answer": "Sinoatrial (SA) node",
            "written_accept": ["sa node", "sinoatrial node", "sinus node"],
            "distractors": ["Atrioventricular node", "Bundle of His", "Purkinje fibers", "Bundle branches"],
        },
        {
            "image": "image111.png",
            "highlight": {"x": 50, "y": 45},
            "question": "Identify the node that receives the impulse from the SA node before it spreads to the ventricles.",
            "answer": "Atrioventricular (AV) node",
            "written_accept": ["av node", "atrioventricular node"],
            "distractors": ["SA node", "Bundle of His", "Purkinje fibers", "Bundle branches"],
        },
        {
            "image": "image111.png",
            "highlight": {"x": 50, "y": 65},
            "question": "Identify the conduction pathway that carries impulses from the AV node into the ventricular septum.",
            "answer": "Bundle of His (AV bundle)",
            "written_accept": ["bundle of his", "av bundle", "atrioventricular bundle"],
            "distractors": ["SA node", "AV node", "Purkinje fibers", "Bundle branches"],
        },
        {
            "image": "image85.png",
            "highlight": {"x": 60, "y": 60},
            "question": "At which intercostal space and location do you auscultate the mitral valve?",
            "answer": "5th intercostal space, midclavicular line",
            "written_accept": ["5th intercostal space midclavicular", "5th intercostal midclavicular line", "5th intercostal space at midclavicular line"],
            "distractors": ["5th intercostal space left sternal border", "2nd intercostal space right sternal border", "2nd intercostal space left sternal border"],
        },
        {
            "image": "image85.png",
            "highlight": {"x": 40, "y": 40},
            "question": "At which intercostal space and location do you auscultate the aortic valve?",
            "answer": "2nd intercostal space, right sternal border",
            "written_accept": ["2nd intercostal space right sternal border", "2nd intercostal right sternal border", "2nd right sternal"],
            "distractors": ["2nd intercostal space left sternal border", "5th intercostal space midclavicular line", "5th intercostal space left sternal border"],
        },
        {
            "image": "image121.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the subdivision of the mediastinum shown here, located posterior to the pericardium.",
            "answer": "Posterior mediastinum",
            "written_accept": ["posterior mediastinum", "posterior"],
            "distractors": ["Anterior mediastinum", "Middle mediastinum", "Superior mediastinum"],
        },
        {
            "image": "image41.png",
            "highlight": {"x": 50, "y": 50},
            "question": "This diagram shows the venous drainage of the superior mediastinum. The internal jugular and subclavian veins join to form which vein?",
            "answer": "Brachiocephalic vein",
            "written_accept": ["brachiocephalic vein", "brachiocephalic", "innominate vein"],
            "distractors": ["Superior vena cava", "Azygos vein", "Subclavian vein", "Internal jugular vein"],
        },
        {
            "image": "image27.png",
            "highlight": {"x": 50, "y": 40},
            "question": "How many branches arise from the aortic arch, as shown in this diagram?",
            "answer": "Three branches",
            "written_accept": ["three", "3", "three branches", "3 branches"],
            "distractors": ["Two branches", "Four branches", "One branch", "Five branches"],
        },
        {
            "image": "image27.png",
            "highlight": {"x": 30, "y": 30},
            "question": "Identify the first and largest branch arising from the aortic arch on the right side.",
            "answer": "Brachiocephalic trunk",
            "written_accept": ["brachiocephalic trunk", "brachiocephalic artery", "innominate artery"],
            "distractors": ["Left common carotid artery", "Left subclavian artery", "Right common carotid artery"],
        },
        {
            "image": "image52.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the muscle in the neck region that has the subclavian artery running behind it and the subclavian vein in front.",
            "answer": "Scalenus anterior",
            "written_accept": ["scalenus anterior", "anterior scalene"],
            "distractors": ["Sternocleidomastoid", "Trapezius", "Levator scapulae", "Scalenus medius"],
        },
        {
            "image": "image9.png",
            "highlight": {"x": 35, "y": 50},
            "question": "Identify the nerve that runs anterior to the scalenus anterior and innervates the diaphragm.",
            "answer": "Phrenic nerve",
            "written_accept": ["phrenic nerve", "phrenic"],
            "distractors": ["Vagus nerve", "Recurrent laryngeal nerve", "Long thoracic nerve", "Accessory nerve"],
        },
        {
            "image": "image65.png",
            "highlight": {"x": 50, "y": 60},
            "question": "Identify the nerve that loops around the aortic arch on the left side before ascending to the larynx.",
            "answer": "Left recurrent laryngeal nerve",
            "written_accept": ["left recurrent laryngeal nerve", "recurrent laryngeal nerve", "left recurrent laryngeal"],
            "distractors": ["Right recurrent laryngeal nerve", "Vagus nerve", "Phrenic nerve", "Accessory nerve"],
        },
    ],
    "upper-limb-1": [
        {
            "image": "image26.png",
            "highlight": {"x": 30, "y": 50},
            "question": "Identify the bone that forms the horizontal strut connecting the sternum to the scapula.",
            "answer": "Clavicle",
            "written_accept": ["clavicle", "collar bone"],
            "distractors": ["Scapula", "Humerus", "Acromion", "Coracoid process"],
        },
        {
            "image": "image26.png",
            "highlight": {"x": 60, "y": 50},
            "question": "Identify the flat triangular bone on the posterior thorax shown here.",
            "answer": "Scapula",
            "written_accept": ["scapula", "shoulder blade"],
            "distractors": ["Clavicle", "Humerus", "Sternum", "Rib"],
        },
        {
            "image": "image29.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the large diamond-shaped muscle shown here that spans from the skull to the thoracic spine.",
            "answer": "Trapezius",
            "written_accept": ["trapezius", "trap"],
            "distractors": ["Latissimus dorsi", "Rhomboids", "Levator scapulae", "Deltoid"],
        },
        {
            "image": "image100.png",
            "highlight": {"x": 40, "y": 50},
            "question": "Identify the large back muscle shown here that performs extension, adduction, and medial rotation of the arm.",
            "answer": "Latissimus dorsi",
            "written_accept": ["latissimus dorsi", "lat", "lats"],
            "distractors": ["Trapezius", "Rhomboids", "Teres major", "Deltoid"],
        },
        {
            "image": "image78.png",
            "highlight": {"x": 40, "y": 50},
            "question": "Identify the muscle that elevates the scapula, running from cervical vertebrae to the medial border of the scapula.",
            "answer": "Levator scapulae",
            "written_accept": ["levator scapulae", "levator"],
            "distractors": ["Trapezius", "Rhomboids", "Serratus anterior", "Sternocleidomastoid"],
        },
        {
            "image": "image147.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the rotator cuff muscle shown here in the infraspinous fossa that laterally rotates the arm.",
            "answer": "Infraspinatus",
            "written_accept": ["infraspinatus"],
            "distractors": ["Supraspinatus", "Teres minor", "Subscapularis", "Teres major"],
        },
        {
            "image": "image148.png",
            "highlight": {"x": 30, "y": 20},
            "question": "Identify the rotator cuff muscle in the supraspinous fossa that initiates shoulder abduction.",
            "answer": "Supraspinatus",
            "written_accept": ["supraspinatus"],
            "distractors": ["Infraspinatus", "Teres minor", "Subscapularis", "Deltoid"],
        },
        {
            "image": "image148.png",
            "highlight": {"x": 25, "y": 55},
            "question": "Identify the rotator cuff muscle on the anterior surface of the scapula that medially rotates the arm.",
            "answer": "Subscapularis",
            "written_accept": ["subscapularis"],
            "distractors": ["Supraspinatus", "Infraspinatus", "Teres minor", "Teres major"],
        },
        {
            "image": "image148.png",
            "highlight": {"x": 55, "y": 45},
            "question": "Identify the muscle posterior to the scapula that extends and adducts the arm at the shoulder.",
            "answer": "Teres major",
            "written_accept": ["teres major"],
            "distractors": ["Teres minor", "Infraspinatus", "Subscapularis", "Latissimus dorsi"],
        },
        {
            "image": "image125.png",
            "highlight": {"x": 50, "y": 20},
            "question": "The brachial plexus originates from which spinal nerve roots?",
            "answer": "C5, C6, C7, C8, T1",
            "written_accept": ["c5 c6 c7 c8 t1", "c5-t1", "c5 to t1"],
            "distractors": ["C3, C4, C5", "C4-C8", "C6-T2", "T1-T5"],
        },
        {
            "image": "image15.png",
            "highlight": {"x": 30, "y": 30},
            "question": "Identify the terminal nerve of the brachial plexus that innervates the biceps and coracobrachialis.",
            "answer": "Musculocutaneous nerve",
            "written_accept": ["musculocutaneous nerve", "musculocutaneous"],
            "distractors": ["Median nerve", "Ulnar nerve", "Radial nerve", "Axillary nerve"],
        },
        {
            "image": "image15.png",
            "highlight": {"x": 50, "y": 70},
            "question": "Identify the terminal nerve of the brachial plexus that passes through the carpal tunnel.",
            "answer": "Median nerve",
            "written_accept": ["median nerve", "median"],
            "distractors": ["Ulnar nerve", "Radial nerve", "Musculocutaneous nerve", "Axillary nerve"],
        },
        {
            "image": "image97.png",
            "highlight": {"x": 30, "y": 30},
            "question": "Identify the main artery of the arm that is a continuation of the axillary artery.",
            "answer": "Brachial artery",
            "written_accept": ["brachial artery", "brachial"],
            "distractors": ["Axillary artery", "Radial artery", "Ulnar artery", "Subclavian artery"],
        },
        {
            "image": "image97.png",
            "highlight": {"x": 60, "y": 50},
            "question": "Identify the nerve shown running posteriorly between the long and lateral heads of the triceps.",
            "answer": "Radial nerve",
            "written_accept": ["radial nerve", "radial"],
            "distractors": ["Ulnar nerve", "Median nerve", "Musculocutaneous nerve", "Axillary nerve"],
        },
        {
            "image": "image114.png",
            "highlight": {"x": 50, "y": 40},
            "question": "Identify the triangular shoulder muscle with anterior, middle, and posterior parts that abducts the arm.",
            "answer": "Deltoid",
            "written_accept": ["deltoid"],
            "distractors": ["Trapezius", "Pectoralis major", "Supraspinatus", "Teres major"],
        },
    ],
    "upper-limb-2": [
        {
            "image": "image42.png",
            "highlight": {"x": 50, "y": 20},
            "question": "Identify the rounded proximal end of the radius that articulates with the capitulum of the humerus.",
            "answer": "Head of radius",
            "written_accept": ["head of radius", "radial head"],
            "distractors": ["Radial tuberosity", "Olecranon process", "Coronoid process", "Radial styloid"],
        },
        {
            "image": "image42.png",
            "highlight": {"x": 40, "y": 40},
            "question": "Identify the bony prominence on the radius where the biceps tendon attaches.",
            "answer": "Radial tuberosity",
            "written_accept": ["radial tuberosity"],
            "distractors": ["Head of radius", "Olecranon process", "Ulnar tuberosity", "Lateral epicondyle"],
        },
        {
            "image": "image140.png",
            "highlight": {"x": 50, "y": 80},
            "question": "Identify the group of small bones at the base of the hand between the forearm and metacarpals.",
            "answer": "Carpals",
            "written_accept": ["carpals", "carpal bones"],
            "distractors": ["Metacarpals", "Phalanges", "Tarsals", "Sesamoid bones"],
        },
        {
            "image": "image140.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the long bones of the palm numbered 1-5 from thumb to pinky.",
            "answer": "Metacarpals",
            "written_accept": ["metacarpals", "metacarpal bones"],
            "distractors": ["Carpals", "Phalanges", "Metatarsals", "Tarsals"],
        },
        {
            "image": "image21.png",
            "highlight": {"x": 30, "y": 30},
            "question": "Identify the first-layer forearm muscle that pronates the forearm and attaches from the medial epicondyle to the radius.",
            "answer": "Pronator teres",
            "written_accept": ["pronator teres"],
            "distractors": ["Flexor carpi radialis", "Palmaris longus", "Flexor carpi ulnaris", "Pronator quadratus"],
        },
        {
            "image": "image21.png",
            "highlight": {"x": 30, "y": 50},
            "question": "Identify the first-layer forearm muscle that attaches from the medial epicondyle to the 2nd and 3rd metacarpals.",
            "answer": "Flexor carpi radialis",
            "written_accept": ["flexor carpi radialis", "fcr"],
            "distractors": ["Pronator teres", "Palmaris longus", "Flexor carpi ulnaris", "Flexor digitorum superficialis"],
        },
        {
            "image": "image21.png",
            "highlight": {"x": 30, "y": 65},
            "question": "Identify the first-layer forearm muscle that attaches from the medial epicondyle to the palmar aponeurosis.",
            "answer": "Palmaris longus",
            "written_accept": ["palmaris longus"],
            "distractors": ["Flexor carpi radialis", "Flexor carpi ulnaris", "Pronator teres", "Flexor digitorum superficialis"],
        },
        {
            "image": "image21.png",
            "highlight": {"x": 30, "y": 80},
            "question": "Identify the first-layer forearm muscle on the ulnar side that attaches from the medial epicondyle to the carpals.",
            "answer": "Flexor carpi ulnaris",
            "written_accept": ["flexor carpi ulnaris", "fcu"],
            "distractors": ["Flexor carpi radialis", "Palmaris longus", "Pronator teres", "Flexor digitorum superficialis"],
        },
        {
            "image": "image119.png",
            "highlight": {"x": 30, "y": 40},
            "question": "Identify the second-layer forearm flexor that attaches to the middle phalanges of four fingers.",
            "answer": "Flexor digitorum superficialis (FDS)",
            "written_accept": ["flexor digitorum superficialis", "fds"],
            "distractors": ["Flexor digitorum profundus", "Flexor pollicis longus", "Pronator quadratus", "Palmaris longus"],
        },
        {
            "image": "image119.png",
            "highlight": {"x": 60, "y": 40},
            "question": "Identify the deep forearm flexor that attaches to the distal phalanges of four fingers.",
            "answer": "Flexor digitorum profundus (FDP)",
            "written_accept": ["flexor digitorum profundus", "fdp"],
            "distractors": ["Flexor digitorum superficialis", "Flexor pollicis longus", "Pronator quadratus", "Palmaris longus"],
        },
        {
            "image": "image50.png",
            "highlight": {"x": 40, "y": 50},
            "question": "Which tendon attaches to the middle phalanx and splits to let the other tendon pass through?",
            "answer": "Flexor digitorum superficialis (FDS)",
            "written_accept": ["flexor digitorum superficialis", "fds"],
            "distractors": ["Flexor digitorum profundus", "Flexor pollicis longus", "Extensor digitorum"],
        },
        {
            "image": "image142.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the posterior forearm muscle that extends all four fingers.",
            "answer": "Extensor digitorum",
            "written_accept": ["extensor digitorum"],
            "distractors": ["Extensor carpi radialis longus", "Extensor carpi ulnaris", "Extensor digiti minimi", "Extensor pollicis longus"],
        },
        {
            "image": "image66.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the posterior forearm muscle shown here on the radial side.",
            "answer": "Brachioradialis",
            "written_accept": ["brachioradialis"],
            "distractors": ["Extensor carpi radialis longus", "Pronator teres", "Flexor carpi radialis", "Supinator"],
        },
        {
            "image": "image70.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the anatomical tunnel at the wrist that contains flexor tendons and the median nerve.",
            "answer": "Carpal tunnel",
            "written_accept": ["carpal tunnel"],
            "distractors": ["Cubital tunnel", "Guyon's canal", "Anatomical snuffbox", "Flexor retinaculum"],
        },
        {
            "image": "image70.png",
            "highlight": {"x": 50, "y": 30},
            "question": "Identify the nerve that passes through the carpal tunnel and can be compressed in carpal tunnel syndrome.",
            "answer": "Median nerve",
            "written_accept": ["median nerve", "median"],
            "distractors": ["Ulnar nerve", "Radial nerve", "Musculocutaneous nerve"],
        },
        {
            "image": "image89.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the intrinsic hand muscles between the metacarpals that abduct the fingers (DAB).",
            "answer": "Dorsal interossei",
            "written_accept": ["dorsal interossei", "dorsal interosseous"],
            "distractors": ["Palmar interossei", "Lumbricals", "Thenar muscles", "Hypothenar muscles"],
        },
        {
            "image": "image122.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Identify the intrinsic hand muscles that adduct the fingers (PAD).",
            "answer": "Palmar interossei",
            "written_accept": ["palmar interossei", "palmar interosseous"],
            "distractors": ["Dorsal interossei", "Lumbricals", "Thenar muscles", "Hypothenar muscles"],
        },
        {
            "image": "image45.png",
            "highlight": {"x": 30, "y": 60},
            "question": "Identify the group of muscles at the base of the thumb.",
            "answer": "Thenar muscles",
            "written_accept": ["thenar muscles", "thenar"],
            "distractors": ["Hypothenar muscles", "Palmar interossei", "Dorsal interossei", "Lumbricals"],
        },
        {
            "image": "image45.png",
            "highlight": {"x": 70, "y": 30},
            "question": "Identify the tough connective tissue sheet in the palm that overlies the flexor tendons.",
            "answer": "Palmar aponeurosis",
            "written_accept": ["palmar aponeurosis"],
            "distractors": ["Flexor retinaculum", "Extensor retinaculum", "Carpal tunnel", "Palmar fascia"],
        },
        {
            "image": "image144.png",
            "highlight": {"x": 50, "y": 50},
            "question": "Which three nerves provide sensory and motor innervation to the hand?",
            "answer": "Median, ulnar, and radial nerves",
            "written_accept": ["median ulnar radial", "median nerve ulnar nerve radial nerve"],
            "distractors": ["Musculocutaneous, axillary, and radial nerves", "Ulnar, median, and axillary nerves", "Radial, ulnar, and long thoracic nerves"],
        },
    ],
}


def main():
    with open(YAML_PATH, "r") as f:
        data = yaml.safe_load(f)

    total_added = 0
    for topic in data["topics"]:
        topic_id = topic["id"]
        if topic_id not in IMAGE_QUESTIONS:
            continue

        existing_ids = {q["id"] for q in topic["questions"]}
        prefix = topic["questions"][-1]["id"].rsplit("-", 1)[0]
        last_num = int(topic["questions"][-1]["id"].rsplit("-", 1)[1])

        for img_q in IMAGE_QUESTIONS[topic_id]:
            last_num += 1
            new_id = f"{prefix}-{last_num:03d}"
            while new_id in existing_ids:
                last_num += 1
                new_id = f"{prefix}-{last_num:03d}"

            question = {
                "id": new_id,
                "type": "image-identify",
                "image": img_q["image"],
                "masks": "all",
                "highlight": img_q["highlight"],
                "question": img_q["question"],
                "answer": img_q["answer"],
                "written_accept": img_q["written_accept"],
                "distractors": img_q["distractors"],
            }
            topic["questions"].append(question)
            existing_ids.add(new_id)
            total_added += 1

        print(f"{topic['name']}: added {len(IMAGE_QUESTIONS[topic_id])} image questions (now {len(topic['questions'])} total)")

    with open(YAML_PATH, "w") as f:
        yaml.dump(data, f, default_flow_style=False, allow_unicode=True, sort_keys=False, width=200)

    print(f"\nTotal added: {total_added}")


if __name__ == "__main__":
    main()
